#!/bin/bash
# Written by Draco (tytydraco) @ GitHub

err() {
	echo -e "\e[91m[!] $@\e[39m"
	exit 1
}

# Path containing rootfs tarball and all rootfs instances
if [[ -d "/home" ]]
then
	CHROOT_DIR="~/charch"
else
	CHROOT_DIR="/data/local/charch"
fi

usage() {
	echo -n "Usage: `basename $0` [OPTIONS]

Options:
  -d DIRECTORY		Specify a chroot container directory (default: $CHROOT_DIR)
  -t			List any existing rootfs tarballs
  -h			Show usage
"
}

while getopts ":d:th" opt; do
	case $opt in
		d)
			CHROOT_DIR="$OPTARG"
			;;
		t)
			LIST_TARBALLS=1
			;;
		h)
			usage
			exit 0
			;;
		*)
			usage
			exit 1
			;;
	esac
done
shift $((OPTIND-1))

# Add busybox components from Magisk
[[ -d "/sbin/.magisk/busybox" ]] && [[ "$PATH" != *"/sbin/.magisk/busybox"* ]] &&
	export PATH="$PATH:/sbin/.magisk/busybox"

# Check for required dependencies
for dep in find id
do
	! command -v "$dep" &> /dev/null && err "Unable to locate dependency $dep. Exiting."
done

# Check for root permissions
[[ `id -u` -ne 0 ]] && err "No root permissions. Exiting."

# Check if chroot container exists
[[ ! -d "$CHROOT_DIR" ]] && err "No container at $CHROOT_DIR. Exiting."

# Display paths to available rootfs instances
if [[ "$LIST_TARBALLS" -eq 1 ]]
then
	find "$CHROOT_DIR" -mindepth 1 -maxdepth 1 -type f -name "*.tar.gz"
else
	find "$CHROOT_DIR" -maxdepth 1 -mindepth 1 -type d
fi
