#!/bin/bash
# Written by Draco (tytydraco) @ GitHub

# Path containing rootfs tarball and all rootfs instances
if [[ -d "/home" ]]
then
	CHROOT_DIR="/home/chroot"
else
	CHROOT_DIR="/data/local/chroot"
fi

usage() {
	echo -n "Usage: `basename $0` [OPTIONS]

Options:
  -d DIRECTORY		Specify a chroot container directory (default: /data/local/chroot/)
  -t			List any existing rootfs tarballs
  -h			Show usage
"
}

while getopts "hd:t" opt; do
	case $opt in
		h)
			usage
			exit 0
			;;
		d)
			CHROOT_DIR="$OPTARG"
			;;
		t)
			LIST_TARBALLS=1
			;;
		?)
			usage
			exit 1
			;;
  esac
done
shift $((OPTIND-1))

# Add busybox components from Magisk
[[ -d "/sbin/.magisk/busybox" ]] && [[ "$PATH" != *"/sbin/.magisk/busybox"* ]] &&
	export PATH="$PATH:/sbin/.magisk/busybox"

# Check for required dependencies
for dep in find id
do
	if ! command -v "$dep" &> /dev/null
	then
		echo "[!] Unable to locate dependency $dep. Exiting."
		exit 1
	fi
done

# Check for root permissions
if [[ `id -u` -ne 0 ]]
then
	echo "[!] No root permissions. Exiting."
	exit 1
fi

# Check if chroot container exists
if [ ! -d "$CHROOT_DIR" ]
then
	echo "[!] No container at $CHROOT_DIR. Exiting."
	exit 1
fi

# Display paths to available rootfs instances
if [[ "$LIST_TARBALLS" -eq 1 ]]
then
	find "$CHROOT_DIR" -mindepth 1 -maxdepth 1 -type f -name "*.tar.gz"
else
	find "$CHROOT_DIR" -maxdepth 1 -mindepth 1 -type d
fi
