#!/bin/bash
# Written by Draco (tytydraco) @ GitHub

usage() {
	echo "Usage:"
	echo "	unarch [-h] [-d directory] [-n name]"
	echo ""
	echo "Unmount a rootfs instance."
	echo ""
	echo "Options:"
	echo "	-h: Show usage"
	echo "	-d: Specify a chroot container directory (default: /data/local/chroot/)"
	echo "	-n: The name of the rootfs instance to unmount (default: rootfs)"
}

while getopts "hd:n:" opt; do
	case $opt in
		h)
			usage
			exit 0
			;;
		d)
			CHROOT_DIR="$OPTARG"
			;;
		n)
			ROOTFS="$OPTARG"
			;;
		?)
			usage
			exit 1
			;;
  esac
done
shift $((OPTIND-1))

# Path containing rootfs tarball and rootfs instances
if [[ -z "$CHROOT_DIR" ]]
then
	# Prefer a standard Linux directory
	if [[ -d "/home" ]]
	then
		CHROOT_DIR="/home/chroot"
	else
		CHROOT_DIR="/data/local/chroot"
	fi
fi

# The name of the current rootfs instance
[[ -z "$ROOTFS" ]] && ROOTFS="rootfs"

# Path to root of rootfs instance
ROOTFS_DIR="$CHROOT_DIR/$ROOTFS"

# Add busybox components from Magisk
[[ -d "/sbin/.magisk/busybox" ]] && [[ "$PATH" != *"/sbin/.magisk/busybox"* ]] &&
	export PATH="$PATH:/sbin/.magisk/busybox"

# Check for required dependencies
for dep in id mount umount awk grep uniq tac
do
	if ! command -v "$dep" &> /dev/null
	then
		echo "[!] Missing $dep. Exiting."
		exit 1
	fi
done

# Check for root permissions
if [[ `id -u` -ne 0 ]]
then
	echo "[!] No root permissions. Exiting."
	exit 1
fi

# Check if rootfs exists
if [[ ! -d "$ROOTFS_DIR" ]]
then
	echo "[!] No instance at $ROOTFS_DIR. Exiting."
	exit 1
fi

# Check if chroot container exists
if [ ! -d "$CHROOT_DIR" ]
then
	echo "[!] No container at $CHROOT_DIR. Exiting."
	exit 1
fi

# Check for optional lsof dependency to automatically kill processes
if command -v lsof &> /dev/null
then
	for pid in `lsof -t "$ROOTFS_DIR"`
	do
		kill "$pid"
	done
fi

# Unmount host binds
_umount() {
	local name="$1"

	# Bind if not already mounted
	if mount | grep -qs " $ROOTFS_DIR/$name "
	then
		umount -f "$ROOTFS_DIR/$name" &> /dev/null

		# Fail check
		if [[ $? -ne 0 ]]
		then
			echo "[!] Failed to unmount $name. Try rebooting. Exiting."
			exit 1
		fi
	fi
}

# Unmount guest filesystems
_umount dev/pts
_umount dev
_umount proc
_umount sys
_umount tmp
