#!/bin/bash
# Written by Draco (tytydraco) @ GitHub

# Path containing rootfs tarball and rootfs instances
if [[ -d "/home" ]]
then
	CHROOT_DIR="/home/chroot"
else
	CHROOT_DIR="/data/local/chroot"
fi

# The name of the current rootfs instance
ROOTFS="rootfs"

usage() {
	echo -n "Usage: `basename $0` [OPTIONS]

Options:
  -d DIRECTORY		Specify a chroot container directory (default: /data/local/chroot/)
  -n NAME		The name of the rootfs instance to unmount (default: rootfs)
  -h			Show usage
"
}

while getopts "hd:n:" opt; do
	case $opt in
		h)
			usage
			exit 0
			;;
		d)
			CHROOT_DIR="$OPTARG"
			;;
		n)
			ROOTFS="$OPTARG"
			;;
		?)
			usage
			exit 1
			;;
	esac
done
shift $((OPTIND-1))

# Path to root of rootfs instance
ROOTFS_DIR="$CHROOT_DIR/$ROOTFS"

# Add busybox components from Magisk
[[ -d "/sbin/.magisk/busybox" ]] && [[ "$PATH" != *"/sbin/.magisk/busybox"* ]] &&
	export PATH="$PATH:/sbin/.magisk/busybox"

# Check for required dependencies
for dep in awk grep id mount mountpoint tac umount uniq
do
	if ! command -v "$dep" &> /dev/null
	then
		echo "[!] Unable to locate dependency $dep. Exiting."
		exit 1
	fi
done

# Check for root permissions
if [[ `id -u` -ne 0 ]]
then
	echo "[!] No root permissions. Exiting."
	exit 1
fi

# Check if rootfs exists
if [[ ! -d "$ROOTFS_DIR" ]]
then
	echo "[!] No instance at $ROOTFS_DIR. Exiting."
	exit 1
fi

# Check if chroot container exists
if [ ! -d "$CHROOT_DIR" ]
then
	echo "[!] No container at $CHROOT_DIR. Exiting."
	exit 1
fi

# Check for optional lsof dependency to automatically kill processes
if command -v lsof &> /dev/null
then
	for pid in `lsof -t "$ROOTFS_DIR"`
	do
		kill "$pid"
	done
fi

# Unmount host binds
_umount() {
	local name="$1"

	# Unmount if not already mounted
	if mountpoint -q "$ROOTFS_DIR/$name" &> /dev/null
	then
		umount -f "$ROOTFS_DIR/$name" &> /dev/null

		# Fail check
		if [[ $? -ne 0 ]]
		then
			echo "[!] Failed to unmount $name. Try rebooting. Exiting."
			exit 1
		fi
	fi
}

# Unmount guest filesystems
_umount dev/pts
_umount dev
_umount proc
_umount sys
_umount tmp
